version: '3'
services:

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./..:/go/src/project"
    depends_on:
      - mysql
    environment:
      - DB_PORT=${MYSQL_PORT}
      - DB_HOST=mysql
    ports:
      - "8000:8000"
    command: go run -mod=vendor /go/src/project/main.go

  mysql:
    image: mysql:5.7
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "3306:3306"
