version: '3'

services:
    postgis:
        image: mdillon/postgis:${POSTGIS_TAG}
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - "postgres_database:/var/lib/postgresql/data"
        ports:
            - "${POSTGIS_MAPPED_PORT}:${POSTGIS_DOCKER_PORT}"

volumes:
    postgres_database: