version: '3'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ssd-minio-user
      MINIO_ROOT_PASSWORD: Nch97nzgL@x=<Sqc
    command: server --console-address ":9001" /data