name: my-local-pg
services:  
  postgres:
    image: postgres
    volumes:
      - my-pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
volumes:
  my-pg-data:     
